import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import Providers from "./providers";
import { Toaster } from "sonner";

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin", "vietnamese"],
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${roboto.variable} h-full antialiased`}
		>
			<body className="font-roboto">
				<Providers>
					<QueryProvider>{children}</QueryProvider>
				</Providers>
				<Toaster />
			</body>
		</html>
	);
}
